# Generated by Django 3.2.7 on 2021-11-14 01:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_student_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Student',
        ),
    ]
