# Generated by Django 3.2.9 on 2021-11-03 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Applcation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('firstname', models.CharField(blank='True', max_length=150)),
                ('lastname', models.CharField(blank='True', max_length=150)),
                ('Gpa', models.CharField(blank='True', max_length=150)),
                ('semester', models.CharField(blank='True', max_length=150)),
                ('Birthday', models.DateField()),
                ('address', models.CharField(max_length=50)),
                ('city', models.CharField(default='NewYork', max_length=60)),
                ('state', models.CharField(default='NewYork', max_length=30)),
                ('zip', models.CharField(default='11220', max_length=5)),
                ('country', models.CharField(max_length=50)),
                ('transcript', models.FileField(upload_to='documents/')),
                ('letters', models.FileField(upload_to='documents/')),
                ('personal_statement', models.FileField(upload_to='documents/')),
                ('major', models.CharField(blank='True', max_length=150)),
            ],
        ),
    ]
