# Generated by Django 3.2.9 on 2021-11-03 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='applcation',
            old_name='transcript',
            new_name='transcprit',
        ),
    ]
