# Generated by Django 2.2.14 on 2021-11-11 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_auto_20211104_1613'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applcation',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
