# Generated by Django 3.2.9 on 2021-11-13 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0004_auto_20211111_1108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applcation',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
