# Generated by Django 3.2.7 on 2021-11-13 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0005_alter_applcation_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Complaints',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('studentid', models.PositiveIntegerField()),
                ('complainee', models.CharField(max_length=150)),
                ('text', models.CharField(max_length=800)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=150)),
                ('lastname', models.CharField(max_length=150)),
                ('studentid', models.PositiveIntegerField()),
                ('gpa', models.FloatField()),
            ],
        ),
    ]