# Generated by Django 3.2.7 on 2021-11-14 19:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0007_delete_student'),
    ]

    operations = [
        migrations.RenameField(
            model_name='complaints',
            old_name='studentid',
            new_name='user_id',
        ),
    ]
