# Generated by Django 3.2.7 on 2021-11-14 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0008_rename_studentid_complaints_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaints',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
    ]
