# Generated by Django 3.2.7 on 2021-11-14 21:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0009_complaints_is_completed'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Complaints',
            new_name='StudentComplaint',
        ),
    ]
