# Generated by Django 3.2.9 on 2021-11-17 01:03

import account.models
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='CUNY Email')),
                ('username', models.CharField(max_length=200)),
                ('first_name', models.CharField(blank='True', max_length=150)),
                ('last_name', models.CharField(blank='True', max_length=150)),
                ('last_login', models.DateTimeField(auto_now=True, verbose_name='last login')),
                ('is_instructor', models.BooleanField(default=False, verbose_name='is instrutor')),
                ('is_student', models.BooleanField(default=False, verbose_name='is student')),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_admin', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('First_login', models.BooleanField(default=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('object', django.db.models.manager.Manager()),
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Instructor',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='account.user')),
                ('first_name', models.CharField(blank='True', max_length=150)),
                ('last_name', models.CharField(blank='True', max_length=150)),
                ('email', models.EmailField(max_length=254, unique=True, validators=[account.models.validate_mail], verbose_name='email address')),
                ('ID', models.PositiveIntegerField(default=0)),
                ('warning', models.PositiveSmallIntegerField(default=0)),
                ('is_warned', models.BooleanField(default=False)),
                ('is_suspanded', models.BooleanField(default=False)),
                ('is_working', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='account.user')),
                ('first_name', models.CharField(blank='True', max_length=150)),
                ('last_name', models.CharField(blank='True', max_length=150)),
                ('email', models.EmailField(max_length=254, unique=True, validators=[account.models.validate_mail], verbose_name='email address')),
                ('ID', models.PositiveIntegerField(default=0)),
                ('warning', models.PositiveSmallIntegerField(default=0)),
                ('is_warned', models.BooleanField(default=False)),
                ('GPA', models.IntegerField(default=0)),
                ('is_suspended', models.BooleanField(default=False)),
                ('is_graduate', models.BooleanField(default=False)),
            ],
        ),
    ]
