# Generated by Django 3.2.7 on 2021-11-14 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_auto_20211113_1328'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='warning',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
